import useSWR from 'swr'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const fetcher = (url) => fetch(url).then((res) => res.json());

export default function Home() {
  const { data, error } = useSWR('/api/hello', fetcher)
  // const fetchSpecial = async () => {
  //   setSpecial(await fetch('https://api.sheridan.edu/specials/').then(res => res.json()));
  // }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sheridan&apos;s Special
        </h1>

        {/* <button onClick={fetchSpecial}>Get Special</button> */}

        <h2>Data</h2>
        {JSON.stringify(data, null, 2)}
        <hr />
        <h2>Error</h2>
        {JSON.stringify(error, null, 2)}


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
